### ISSUE TITLE
Không liên quan đến code

### ISSUE THREAD

**Issue by lv2211** [PersieDaCoder/PokemonManagingApp#1]
M work cùng Lê Nhật Sang à =))) bất ngờ đó chứ @PersieDaCoder

**Comment by PersieDaCoder** [comment]
Wtf t còn đ nhớ là ai :))

Vào 23:08 T.3, 8 Th10, 2024 Vũ Long ***@***.***> đã viết:

**Comment by lv2211** [comment]
Thịnh bịp :)))
